import type { Logger } from '../../utils/log.js';

export type DownloadCommandParams = {
  sessionPath: string;
  outputDir: string;
  courseId: number;
  chapters?: number[];
  chapterRange?: string;
  lessonIds?: number[];
  maxConcurrency: number;
  firstLectureOnly: boolean;
  transcribe: boolean;
  transcribeModel: string;
  transcribeFormat: 'txt' | 'srt' | 'vtt';
  transcribeLanguage?: string;
  noSpeechThreshold?: number;
  maxSeconds?: number;
  materials: boolean;
  deleteMediaAfterTranscribe: boolean;
  ocrMaterials: boolean;
  ocrBackend: 'local' | 'gemini';
  ocrModel: string;
  ocrForce: boolean;
  ocrMode?: 'auto' | 'batch' | 'flex';
  ocrServiceTier?: 'flex' | 'standard';
  ocrRetries?: number;
  ocrTimeoutMs?: number;
  ndlocrCommand: string;
  ndlocrDevice: 'cpu' | 'cuda';
  ocrPageDpi: number;
  ocrKeepIntermediates: boolean;
  ndlocrEnableTcy: boolean;
  geminiApiKey?: string;
  logger: Logger;
};
